/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.AuthorizationType
import net.torrow.api.models.ExternalAuthorizationSolutionData
import net.torrow.api.models.ExternalServiceType

/**
 * 
 * @param name 
 * @param authorizationType 
 * @param externalServiceType 
 * @param solutionData 
 * @param successRedirectUri 
 * @param errorRedirectUri 
 */
data class AddExternalAuthReq (

    val name: kotlin.String,
    val authorizationType: AuthorizationType,
    val externalServiceType: ExternalServiceType,
    val solutionData: ExternalAuthorizationSolutionData,
    val successRedirectUri: kotlin.String,
    val errorRedirectUri: kotlin.String
) {
}