/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.ContactSummary
import net.torrow.api.models.ItemSummary
import net.torrow.api.models.ServiceSummary

/**
 * 
 * @param title 
 * @param serviceSummary 
 * @param firstExecutorSummary 
 * @param restExecutorsCount 
 * @param firstConsumerSummary 
 * @param restConsumersCount 
 * @param firstResourceSummary 
 * @param restResourcesCount 
 * @param currencyCode 
 * @param salePrice 
 * @param place 
 * @param maxConsumerQuantity 
 */
data class CaseSummary (

    val title: kotlin.String? = null,
    val serviceSummary: ServiceSummary? = null,
    val firstExecutorSummary: ContactSummary? = null,
    val restExecutorsCount: kotlin.String? = null,
    val firstConsumerSummary: ContactSummary? = null,
    val restConsumersCount: kotlin.String? = null,
    val firstResourceSummary: ItemSummary? = null,
    val restResourcesCount: kotlin.String? = null,
    val currencyCode: kotlin.String? = null,
    val salePrice: kotlin.Double? = null,
    val place: kotlin.String? = null,
    val maxConsumerQuantity: kotlin.Double? = null
) {
}