/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.AgentType
import net.torrow.api.models.CaseParticipantState
import net.torrow.api.models.CaseParticipantType
import net.torrow.api.models.ConfirmationWaitingState
import net.torrow.api.models.UserType

/**
 * 
 * @param caseParticipantTypeList 
 * @param caseParticipantStateList 
 * @param agentTypeList 
 * @param userType 
 * @param confirmationWaitingState 
 */
data class CaseParticipantFilter (

    val caseParticipantTypeList: kotlin.Array<CaseParticipantType>? = null,
    val caseParticipantStateList: kotlin.Array<CaseParticipantState>? = null,
    val agentTypeList: kotlin.Array<AgentType>? = null,
    val userType: UserType? = null,
    val confirmationWaitingState: ConfirmationWaitingState? = null
) {
}