/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.ActivityStatus
import net.torrow.api.models.ContactVisitCard
import net.torrow.api.models.FileInfo
import net.torrow.api.models.HighlightedField
import net.torrow.api.models.ItemLink
import net.torrow.api.models.PersonalViewInfo
import net.torrow.api.models.ProfileProperties
import net.torrow.api.models.ProfileType
import net.torrow.api.models.PublicityType
import net.torrow.api.models.TorrowObject

/**
 * 
 * @param profileType 
 * @param profileProperties 
 * @param activityStatus 
 * @param visitCard 
 * @param itemObject 
 * @param itemLink 
 * @param personalViewInfo 
 * @param image 
 * @param name 
 * @param isBlocked 
 * @param isCopy 
 * @param publicityType 
 * @param masterItemId 
 * @param highlightedFields 
 */
data class ContactView (

    val profileType: ProfileType? = null,
    val profileProperties: ProfileProperties? = null,
    val activityStatus: ActivityStatus? = null,
    val visitCard: ContactVisitCard? = null,
    val itemObject: TorrowObject? = null,
    val itemLink: ItemLink? = null,
    val personalViewInfo: PersonalViewInfo? = null,
    val image: FileInfo? = null,
    val name: kotlin.String? = null,
    val isBlocked: kotlin.Boolean? = null,
    val isCopy: kotlin.Boolean? = null,
    val publicityType: PublicityType? = null,
    val masterItemId: kotlin.String? = null,
    val highlightedFields: kotlin.Array<HighlightedField>? = null
) {
}