/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.ActivityStatus
import net.torrow.api.models.Address
import net.torrow.api.models.AnyoneAccess
import net.torrow.api.models.BlockInfo
import net.torrow.api.models.ChildItemStat
import net.torrow.api.models.Communication
import net.torrow.api.models.ContactPersonalInfo
import net.torrow.api.models.ContactProperties
import net.torrow.api.models.ContactVisitCard
import net.torrow.api.models.FeedbackOptions
import net.torrow.api.models.FileInfo
import net.torrow.api.models.Gender
import net.torrow.api.models.GroupInfo
import net.torrow.api.models.MasterInfo
import net.torrow.api.models.MemorableDate
import net.torrow.api.models.ObjectInfo
import net.torrow.api.models.ProfileProperties
import net.torrow.api.models.ProfileType
import net.torrow.api.models.PublicityType
import net.torrow.api.models.Rating
import net.torrow.api.models.RegisterInfo
import net.torrow.api.models.SearchMode
import net.torrow.api.models.SolutionData

/**
 * 
 * @param addresses 
 * @param birthday 
 * @param communications 
 * @param dates 
 * @param firstName 
 * @param lastName 
 * @param middleName 
 * @param company 
 * @param position 
 * @param description 
 * @param gender 
 * @param registerInfo 
 * @param photos 
 * @param visitCard 
 * @param profileType 
 * @param activityStatus 
 * @param profileProperties 
 * @param contactProperties 
 * @param personalInfo 
 * @param hasTimetable 
 * @param name 
 * @param uniqueName 
 * @param image 
 * @param masterInfo 
 * @param publicityType 
 * @param searchMode 
 * @param anyoneAccess 
 * @param tags 
 * @param rating 
 * @param blockInfo 
 * @param groupInfo 
 * @param solutionData 
 * @param childItemStats 
 * @param feedbackOptions 
 * @param integrationIds 
 * @param id 
 * @param meta 
 */
data class ContactItem (

    val addresses: kotlin.Array<Address>? = null,
    val birthday: java.time.LocalDateTime? = null,
    val communications: kotlin.Array<Communication>? = null,
    val dates: kotlin.Array<MemorableDate>? = null,
    val firstName: kotlin.String? = null,
    val lastName: kotlin.String? = null,
    val middleName: kotlin.String? = null,
    val company: kotlin.String? = null,
    val position: kotlin.String? = null,
    val description: kotlin.String? = null,
    val gender: Gender? = null,
    val registerInfo: RegisterInfo? = null,
    val photos: kotlin.Array<FileInfo>? = null,
    val visitCard: ContactVisitCard? = null,
    val profileType: ProfileType? = null,
    val activityStatus: ActivityStatus? = null,
    val profileProperties: ProfileProperties? = null,
    val contactProperties: ContactProperties? = null,
    val personalInfo: ContactPersonalInfo? = null,
    val hasTimetable: kotlin.Boolean? = null,
    val name: kotlin.String? = null,
    val uniqueName: kotlin.String? = null,
    val image: FileInfo? = null,
    val masterInfo: MasterInfo? = null,
    val publicityType: PublicityType? = null,
    val searchMode: SearchMode? = null,
    val anyoneAccess: AnyoneAccess? = null,
    val tags: kotlin.Array<kotlin.String>? = null,
    val rating: Rating? = null,
    val blockInfo: BlockInfo? = null,
    val groupInfo: GroupInfo? = null,
    val solutionData: SolutionData? = null,
    val childItemStats: kotlin.Array<ChildItemStat>? = null,
    val feedbackOptions: FeedbackOptions? = null,
    val integrationIds: kotlin.Array<kotlin.String>? = null,
    val id: kotlin.String? = null,
    val meta: ObjectInfo? = null
) {
}