/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.DeviceType
import net.torrow.api.models.OS
import net.torrow.api.models.ObjectInfo

/**
 * 
 * @param deviceId 
 * @param deviceType 
 * @param firebaseToken 
 * @param description 
 * @param os 
 * @param info 
 */
data class DeviceInfo (

    val deviceId: kotlin.String? = null,
    val deviceType: DeviceType? = null,
    val firebaseToken: kotlin.String? = null,
    val description: kotlin.String? = null,
    val os: OS? = null,
    val info: ObjectInfo? = null
) {
}