/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.ServiceStructure
import net.torrow.api.models.WorkloadInfo

/**
 * 
 * @param workloadInfoList 
 * @param serviceStructureList 
 */
data class GetServiceWorkloadInfoResp (

    val workloadInfoList: kotlin.Array<WorkloadInfo>? = null,
    val serviceStructureList: kotlin.Array<ServiceStructure>? = null
) {
}