/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.GroupItemProperties

/**
 * 
 * @param itemPropertiesList 
 * @param parentId 
 * @param groupIds 
 * @param recursive 
 * @param versionToCheck 
 * @param isNeedAnnouncement 
 */
data class IncludeToGroupsReq (

    val itemPropertiesList: kotlin.Array<GroupItemProperties>,
    val parentId: kotlin.String? = null,
    val groupIds: kotlin.Array<kotlin.String>,
    val recursive: kotlin.Boolean? = null,
    val versionToCheck: kotlin.Int? = null,
    val isNeedAnnouncement: kotlin.Boolean? = null
) {
}