/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.AccountingProductName
import net.torrow.api.models.AnyoneAccess
import net.torrow.api.models.BlockInfo
import net.torrow.api.models.ChildItemStat
import net.torrow.api.models.FeedbackOptions
import net.torrow.api.models.FileInfo
import net.torrow.api.models.GroupInfo
import net.torrow.api.models.InitialSubscription
import net.torrow.api.models.LoyaltyCardIssueType
import net.torrow.api.models.LoyaltyCardUpdateKeyInformation
import net.torrow.api.models.LoyaltyCardUpdateNonKeyInformation
import net.torrow.api.models.MasterInfo
import net.torrow.api.models.NumeratorInfo
import net.torrow.api.models.ObjectInfo
import net.torrow.api.models.ParticipateFieldRequirements
import net.torrow.api.models.PersonalInfo
import net.torrow.api.models.PublicityType
import net.torrow.api.models.Rating
import net.torrow.api.models.SearchMode
import net.torrow.api.models.SolutionData
import net.torrow.api.models.TransactionValue

/**
 * 
 * @param description 
 * @param businessCardId 
 * @param loyaltyCardIssueType 
 * @param loyaltyCardAnyoneAccess 
 * @param loyaltyCardUpdateKeyInformation 
 * @param loyaltyCardUpdateNonKeyInformation 
 * @param numeratorInfo 
 * @param loyaltyCardUsagePeriod 
 * @param startDate 
 * @param expiredDate 
 * @param contactInformationFieldsRequirements 
 * @param referralProgramIds 
 * @param beginTransactionValues 
 * @param initialSubscription 
 * @param accountingProductNames 
 * @param name 
 * @param uniqueName 
 * @param image 
 * @param masterInfo 
 * @param publicityType 
 * @param searchMode 
 * @param anyoneAccess 
 * @param tags 
 * @param rating 
 * @param personalInfo 
 * @param blockInfo 
 * @param groupInfo 
 * @param solutionData 
 * @param childItemStats 
 * @param feedbackOptions 
 * @param integrationIds 
 * @param id 
 * @param meta 
 */
data class LoyaltySystemItem (

    val description: kotlin.String? = null,
    val businessCardId: kotlin.String? = null,
    val loyaltyCardIssueType: LoyaltyCardIssueType? = null,
    val loyaltyCardAnyoneAccess: AnyoneAccess? = null,
    val loyaltyCardUpdateKeyInformation: LoyaltyCardUpdateKeyInformation? = null,
    val loyaltyCardUpdateNonKeyInformation: LoyaltyCardUpdateNonKeyInformation? = null,
    val numeratorInfo: NumeratorInfo? = null,
    val loyaltyCardUsagePeriod: kotlin.Int? = null,
    val startDate: java.time.LocalDateTime? = null,
    val expiredDate: java.time.LocalDateTime? = null,
    val contactInformationFieldsRequirements: ParticipateFieldRequirements? = null,
    val referralProgramIds: kotlin.Array<kotlin.String>? = null,
    val beginTransactionValues: kotlin.Array<TransactionValue>? = null,
    val initialSubscription: InitialSubscription? = null,
    val accountingProductNames: kotlin.Array<AccountingProductName>? = null,
    val name: kotlin.String? = null,
    val uniqueName: kotlin.String? = null,
    val image: FileInfo? = null,
    val masterInfo: MasterInfo? = null,
    val publicityType: PublicityType? = null,
    val searchMode: SearchMode? = null,
    val anyoneAccess: AnyoneAccess? = null,
    val tags: kotlin.Array<kotlin.String>? = null,
    val rating: Rating? = null,
    val personalInfo: PersonalInfo? = null,
    val blockInfo: BlockInfo? = null,
    val groupInfo: GroupInfo? = null,
    val solutionData: SolutionData? = null,
    val childItemStats: kotlin.Array<ChildItemStat>? = null,
    val feedbackOptions: FeedbackOptions? = null,
    val integrationIds: kotlin.Array<kotlin.String>? = null,
    val id: kotlin.String? = null,
    val meta: ObjectInfo? = null
) {
}