/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.DeliveryChannelMessage
import net.torrow.api.models.DeliveryStrategy

/**
 * 
 * @param deliveryStrategy 
 * @param deliveryChannelMessageList 
 * @param beginAcceptableTime 
 * @param endAcceptableTime 
 */
data class NotificationProperties (

    val deliveryStrategy: DeliveryStrategy? = null,
    val deliveryChannelMessageList: kotlin.Array<DeliveryChannelMessage>? = null,
    val beginAcceptableTime: kotlin.Int? = null,
    val endAcceptableTime: kotlin.Int? = null
) {
}