/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models


/**
 * 
 * Values: UNKNOWNPARTICIPANTSTATE,REQUESTED,OFFERED,REVOKED,ACCEPTED,REJECTED,DECLINED
 */
enum class ParticipantState(val value: kotlin.String){
    UNKNOWNPARTICIPANTSTATE("UnknownParticipantState"),// :/
    REQUESTED("Requested"),// :/
    OFFERED("Offered"),// :/
    REVOKED("Revoked"),// :/
    ACCEPTED("Accepted"),// :/
    REJECTED("Rejected"),// :/
    DECLINED("Declined");// :/
}