/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.ReportDeliveryType

/**
 * 
 * @param reportDeliveryType 
 * @param reportDeliveryAddresses 
 * @param language 
 * @param timeZone 
 */
data class ReportOptions (

    val reportDeliveryType: ReportDeliveryType,
    val reportDeliveryAddresses: kotlin.Array<kotlin.String>? = null,
    val language: kotlin.String,
    val timeZone: kotlin.String
) {
}