/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.AmountProperties
import net.torrow.api.models.AnyoneAccess
import net.torrow.api.models.Appendix
import net.torrow.api.models.BlockInfo
import net.torrow.api.models.ChildItemStat
import net.torrow.api.models.FeedbackOptions
import net.torrow.api.models.FileInfo
import net.torrow.api.models.GroupInfo
import net.torrow.api.models.LoyaltyTransactionProperties
import net.torrow.api.models.MasterInfo
import net.torrow.api.models.ObjectInfo
import net.torrow.api.models.PaymentProperties
import net.torrow.api.models.PersonalInfo
import net.torrow.api.models.PriceProperties
import net.torrow.api.models.PublicityType
import net.torrow.api.models.Rating
import net.torrow.api.models.Schedule
import net.torrow.api.models.SearchMode
import net.torrow.api.models.ServiceDescription
import net.torrow.api.models.SolutionData
import net.torrow.api.models.TicketProperties
import net.torrow.api.models.TorrowItem
import net.torrow.api.models.UsageCondition
import net.torrow.api.models.UsageType

/**
 * 
 * @param description 
 * @param itemId 
 * @param parentResourceId 
 * @param timetableId 
 * @param schedule 
 * @param item 
 * @param parentResource 
 * @param usageType 
 * @param serviceDescriptions 
 * @param code 
 * @param duration 
 * @param priceProperties 
 * @param amountProperties 
 * @param usageCondition 
 * @param appendixList 
 * @param paymentProperties 
 * @param ticketProperties 
 * @param loyaltyTransactionPropertiesList 
 * @param name 
 * @param uniqueName 
 * @param image 
 * @param masterInfo 
 * @param publicityType 
 * @param searchMode 
 * @param anyoneAccess 
 * @param tags 
 * @param rating 
 * @param personalInfo 
 * @param blockInfo 
 * @param groupInfo 
 * @param solutionData 
 * @param childItemStats 
 * @param feedbackOptions 
 * @param integrationIds 
 * @param id 
 * @param meta 
 */
data class ResourceItem (

    val description: kotlin.String? = null,
    val itemId: kotlin.String? = null,
    val parentResourceId: kotlin.String? = null,
    val timetableId: kotlin.String? = null,
    val schedule: Schedule? = null,
    val item: TorrowItem? = null,
    val parentResource: TorrowItem? = null,
    val usageType: UsageType? = null,
    val serviceDescriptions: kotlin.Array<ServiceDescription>? = null,
    val code: kotlin.String? = null,
    val duration: kotlin.Int? = null,
    val priceProperties: PriceProperties? = null,
    val amountProperties: AmountProperties? = null,
    val usageCondition: UsageCondition? = null,
    val appendixList: kotlin.Array<Appendix>? = null,
    val paymentProperties: PaymentProperties? = null,
    val ticketProperties: TicketProperties? = null,
    val loyaltyTransactionPropertiesList: kotlin.Array<LoyaltyTransactionProperties>? = null,
    val name: kotlin.String? = null,
    val uniqueName: kotlin.String? = null,
    val image: FileInfo? = null,
    val masterInfo: MasterInfo? = null,
    val publicityType: PublicityType? = null,
    val searchMode: SearchMode? = null,
    val anyoneAccess: AnyoneAccess? = null,
    val tags: kotlin.Array<kotlin.String>? = null,
    val rating: Rating? = null,
    val personalInfo: PersonalInfo? = null,
    val blockInfo: BlockInfo? = null,
    val groupInfo: GroupInfo? = null,
    val solutionData: SolutionData? = null,
    val childItemStats: kotlin.Array<ChildItemStat>? = null,
    val feedbackOptions: FeedbackOptions? = null,
    val integrationIds: kotlin.Array<kotlin.String>? = null,
    val id: kotlin.String? = null,
    val meta: ObjectInfo? = null
) {
}