/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.Appendix
import net.torrow.api.models.FileInfo
import net.torrow.api.models.HighlightedField
import net.torrow.api.models.ItemLink
import net.torrow.api.models.ParticipateFieldRequirements
import net.torrow.api.models.PersonalViewInfo
import net.torrow.api.models.PublicityType
import net.torrow.api.models.ResourceGroup
import net.torrow.api.models.SessionDurationProperties
import net.torrow.api.models.TorrowObject

/**
 * 
 * @param description 
 * @param contactId 
 * @param placeId 
 * @param place 
 * @param bookingDuration 
 * @param registrationOpen 
 * @param registrationClose 
 * @param clientGroupId 
 * @param participateFieldRequirements 
 * @param appendixList 
 * @param resourceGroupList 
 * @param sessionDurationProperties 
 * @param checkInAllCases 
 * @param tags 
 * @param itemObject 
 * @param itemLink 
 * @param personalViewInfo 
 * @param image 
 * @param name 
 * @param isBlocked 
 * @param isCopy 
 * @param publicityType 
 * @param masterItemId 
 * @param highlightedFields 
 */
data class ServiceView (

    val description: kotlin.String? = null,
    val contactId: kotlin.String? = null,
    val placeId: kotlin.String? = null,
    val place: kotlin.String? = null,
    val bookingDuration: kotlin.Long? = null,
    val registrationOpen: kotlin.Long? = null,
    val registrationClose: kotlin.Long? = null,
    val clientGroupId: kotlin.String? = null,
    val participateFieldRequirements: ParticipateFieldRequirements? = null,
    val appendixList: kotlin.Array<Appendix>? = null,
    val resourceGroupList: kotlin.Array<ResourceGroup>? = null,
    val sessionDurationProperties: SessionDurationProperties? = null,
    val checkInAllCases: kotlin.Boolean? = null,
    val tags: kotlin.Array<kotlin.String>? = null,
    val itemObject: TorrowObject? = null,
    val itemLink: ItemLink? = null,
    val personalViewInfo: PersonalViewInfo? = null,
    val image: FileInfo? = null,
    val name: kotlin.String? = null,
    val isBlocked: kotlin.Boolean? = null,
    val isCopy: kotlin.Boolean? = null,
    val publicityType: PublicityType? = null,
    val masterItemId: kotlin.String? = null,
    val highlightedFields: kotlin.Array<HighlightedField>? = null
) {
}