/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.ParticipantType

/**
 * 
 * @param rolesToInclude 
 * @param rolesToReadItems 
 * @param rolesToSearchItems 
 * @param rolesToUpdateItems 
 * @param rolesToReadSubscribers 
 * @param rolesToSearchSubscribers 
 * @param versionToCheck 
 * @param isNeedAnnouncement 
 */
data class SetGroupItemReq (

    val rolesToInclude: kotlin.Array<ParticipantType>? = null,
    val rolesToReadItems: kotlin.Array<ParticipantType>? = null,
    val rolesToSearchItems: kotlin.Array<ParticipantType>? = null,
    val rolesToUpdateItems: kotlin.Array<ParticipantType>? = null,
    val rolesToReadSubscribers: kotlin.Array<ParticipantType>? = null,
    val rolesToSearchSubscribers: kotlin.Array<ParticipantType>? = null,
    val versionToCheck: kotlin.Int? = null,
    val isNeedAnnouncement: kotlin.Boolean? = null
) {
}