/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.Metrics
import net.torrow.api.models.ViewBlockSettings

/**
 * 
 * @param quickFilterTags 
 * @param metrics 
 * @param surveyId 
 * @param viewBlockSettings 
 * @param layoutType 
 * @param homeItemIds 
 */
data class SolutionData (

    val quickFilterTags: kotlin.Array<kotlin.String>? = null,
    val metrics: Metrics? = null,
    val surveyId: kotlin.String? = null,
    val viewBlockSettings: ViewBlockSettings? = null,
    val layoutType: kotlin.Int? = null,
    val homeItemIds: kotlin.Array<kotlin.String>? = null
) {
}