/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.AvailabilityTime
import net.torrow.api.models.BookingResourceFilter
import net.torrow.api.models.CaseParticipantState
import net.torrow.api.models.CaseParticipantType
import net.torrow.api.models.CaseState
import net.torrow.api.models.CaseType

/**
 * 
 * @param from 
 * @param to 
 * @param caseStateList 
 * @param caseTypeList 
 * @param caseParticipantTypeList 
 * @param caseParticipantStateList 
 * @param availabilityTimeList 
 * @param profileIdList 
 * @param serviceIdList 
 * @param caseIdListToExclude 
 * @param hasService 
 * @param strictlyInTimeRange 
 * @param bookingResourceFilter 
 */
data class TimetableFilter (

    val from: java.time.LocalDateTime? = null,
    val to: java.time.LocalDateTime? = null,
    val caseStateList: kotlin.Array<CaseState>? = null,
    val caseTypeList: kotlin.Array<CaseType>? = null,
    val caseParticipantTypeList: kotlin.Array<CaseParticipantType>? = null,
    val caseParticipantStateList: kotlin.Array<CaseParticipantState>? = null,
    val availabilityTimeList: kotlin.Array<AvailabilityTime>? = null,
    val profileIdList: kotlin.Array<kotlin.String>? = null,
    val serviceIdList: kotlin.Array<kotlin.String>? = null,
    val caseIdListToExclude: kotlin.Array<kotlin.String>? = null,
    val hasService: kotlin.Boolean? = null,
    val strictlyInTimeRange: kotlin.Boolean? = null,
    val bookingResourceFilter: BookingResourceFilter? = null
) {
}