/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.AccountType
import net.torrow.api.models.ObjectInfo

/**
 * 
 * @param meta 
 * @param name 
 * @param type 
 * @param region 
 * @param userId 
 */
data class Account (

    val meta: ObjectInfo? = null,
    val name: kotlin.String? = null,
    val type: AccountType? = null,
    val region: kotlin.Int? = null,
    val userId: kotlin.String? = null
) {
}