/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.ActionHistoryState
import net.torrow.api.models.ActionHistoryType
import net.torrow.api.models.CalendarView
import net.torrow.api.models.CaseView
import net.torrow.api.models.ContactView
import net.torrow.api.models.ContextView
import net.torrow.api.models.NoteView
import net.torrow.api.models.ObjectInfo
import net.torrow.api.models.ResourceView
import net.torrow.api.models.ServiceView

/**
 * 
 * @param itemContactView 
 * @param itemContextView 
 * @param itemNoteView 
 * @param itemCaseView 
 * @param itemCalendarView 
 * @param itemServiceView 
 * @param itemResourceView 
 * @param userProfileView 
 * @param correspondentProfileViewList 
 * @param actionHistoryType 
 * @param state 
 * @param userMessage 
 * @param text 
 * @param id 
 * @param meta 
 */
data class ActionHistoryInfo (

    val itemContactView: ContactView? = null,
    val itemContextView: ContextView? = null,
    val itemNoteView: NoteView? = null,
    val itemCaseView: CaseView? = null,
    val itemCalendarView: CalendarView? = null,
    val itemServiceView: ServiceView? = null,
    val itemResourceView: ResourceView? = null,
    val userProfileView: ContactView? = null,
    val correspondentProfileViewList: kotlin.Array<ContactView>? = null,
    val actionHistoryType: ActionHistoryType? = null,
    val state: ActionHistoryState? = null,
    val userMessage: kotlin.String? = null,
    val text: kotlin.String? = null,
    val id: kotlin.String? = null,
    val meta: ObjectInfo? = null
) {
}