/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models


/**
 * 
 * Values: UNKNOWNANNOUNCEMENTCATEGORY,ACTION,ALERT,INFORM,SUCCESS,DELETED,ANALYTICS,REMINDER
 */
enum class AnnouncementCategory(val value: kotlin.String){
    UNKNOWNANNOUNCEMENTCATEGORY("UnknownAnnouncementCategory"),// :/
    ACTION("Action"),// :/
    ALERT("Alert"),// :/
    INFORM("Inform"),// :/
    SUCCESS("Success"),// :/
    DELETED("Deleted"),// :/
    ANALYTICS("Analytics"),// :/
    REMINDER("Reminder");// :/
}