/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.Appendix
import net.torrow.api.models.CaseParticipant
import net.torrow.api.models.CaseState
import net.torrow.api.models.CaseType
import net.torrow.api.models.CaseVisitCard
import net.torrow.api.models.FileInfo
import net.torrow.api.models.HighlightedField
import net.torrow.api.models.ItemLink
import net.torrow.api.models.ParticipateFieldRequirements
import net.torrow.api.models.PersonalViewInfo
import net.torrow.api.models.PublicityType
import net.torrow.api.models.ResourceGroup
import net.torrow.api.models.Schedule
import net.torrow.api.models.TorrowObject

/**
 * 
 * @param caseState 
 * @param caseType 
 * @param endDate 
 * @param beginDate 
 * @param visitCard 
 * @param schedule 
 * @param groupId 
 * @param caseParticipant 
 * @param registrationOpen 
 * @param registrationClose 
 * @param hidden 
 * @param appendixList 
 * @param participateFieldRequirements 
 * @param resourceGroupList 
 * @param itemObject 
 * @param itemLink 
 * @param personalViewInfo 
 * @param image 
 * @param name 
 * @param isBlocked 
 * @param isCopy 
 * @param publicityType 
 * @param masterItemId 
 * @param highlightedFields 
 */
data class CaseView (

    val caseState: CaseState? = null,
    val caseType: CaseType? = null,
    val endDate: java.time.LocalDateTime? = null,
    val beginDate: java.time.LocalDateTime? = null,
    val visitCard: CaseVisitCard? = null,
    val schedule: Schedule? = null,
    val groupId: kotlin.String? = null,
    val caseParticipant: CaseParticipant? = null,
    val registrationOpen: kotlin.Int? = null,
    val registrationClose: kotlin.Int? = null,
    val hidden: kotlin.Boolean? = null,
    val appendixList: kotlin.Array<Appendix>? = null,
    val participateFieldRequirements: ParticipateFieldRequirements? = null,
    val resourceGroupList: kotlin.Array<ResourceGroup>? = null,
    val itemObject: TorrowObject? = null,
    val itemLink: ItemLink? = null,
    val personalViewInfo: PersonalViewInfo? = null,
    val image: FileInfo? = null,
    val name: kotlin.String? = null,
    val isBlocked: kotlin.Boolean? = null,
    val isCopy: kotlin.Boolean? = null,
    val publicityType: PublicityType? = null,
    val masterItemId: kotlin.String? = null,
    val highlightedFields: kotlin.Array<HighlightedField>? = null
) {
}