/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models


/**
 * 
 * @param value 
 * @param path 
 * @param op 
 * @param from 
 */
data class CaseItemOperation (

    val value: kotlin.Any? = null,
    val path: kotlin.String? = null,
    val op: kotlin.String? = null,
    val from: kotlin.String? = null
) {
}