/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models


/**
 * 
 * @param itemIds 
 * @param versionToCheck 
 * @param isNeedAnnouncement 
 */
data class ExcludeReq (

    val itemIds: kotlin.Array<kotlin.String>,
    val versionToCheck: kotlin.Int? = null,
    val isNeedAnnouncement: kotlin.Boolean? = null
) {
}