/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.FeedbackMessageReason
import net.torrow.api.models.FeedbackMessageState
import net.torrow.api.models.ObjectInfo
import net.torrow.api.models.TorrowItem

/**
 * 
 * @param messageMeta 
 * @param itemId 
 * @param parentId 
 * @param profileId 
 * @param createDate 
 * @param author 
 * @param messageId 
 * @param changeStateDate 
 * @param state 
 * @param reason 
 * @param header 
 * @param text 
 */
data class Feedback (

    val messageMeta: ObjectInfo? = null,
    val itemId: kotlin.String? = null,
    val parentId: kotlin.String? = null,
    val profileId: kotlin.String? = null,
    val createDate: java.time.LocalDateTime? = null,
    val author: TorrowItem? = null,
    val messageId: kotlin.String? = null,
    val changeStateDate: java.time.LocalDateTime? = null,
    val state: FeedbackMessageState? = null,
    val reason: FeedbackMessageReason? = null,
    val header: kotlin.String? = null,
    val text: kotlin.String? = null
) {
}