/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.OperationType
import net.torrow.api.models.ParticipantState
import net.torrow.api.models.ParticipantType

/**
 * 
 * @param forUser 
 * @param expiresAt 
 * @param operationTypeList 
 * @param participantType 
 * @param participantState 
 * @param roleIdList 
 */
data class GenerateSecurityTokenReq (

    val forUser: kotlin.Boolean? = null,
    val expiresAt: java.time.LocalDateTime? = null,
    val operationTypeList: kotlin.Array<OperationType>? = null,
    val participantType: ParticipantType? = null,
    val participantState: ParticipantState? = null,
    val roleIdList: kotlin.Array<kotlin.Int>? = null
) {
}