/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models


/**
 * 
 * @param id 
 * @param version 
 * @param currentVersion 
 * @param currentName 
 */
data class MasterInfo (

    val id: kotlin.String? = null,
    val version: kotlin.Int? = null,
    val currentVersion: kotlin.Int? = null,
    val currentName: kotlin.String? = null
) {
}