/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models


/**
 * 
 * Values: UNKNOWN,TEXT,HTML,HLINK,FILE,PHOTO,VOICE,GEOLOCATION,QR,SERVICESPECIFICATION
 */
enum class NoteType(val value: kotlin.String){
    UNKNOWN("Unknown"),// :/
    TEXT("Text"),// :/
    HTML("Html"),// :/
    HLINK("Hlink"),// :/
    FILE("File"),// :/
    PHOTO("Photo"),// :/
    VOICE("Voice"),// :/
    GEOLOCATION("Geolocation"),// :/
    QR("Qr"),// :/
    SERVICESPECIFICATION("ServiceSpecification");// :/
}