/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.NotificationWay
import net.torrow.api.models.ObjectInfo
import net.torrow.api.models.ParticipantState
import net.torrow.api.models.ParticipantType
import net.torrow.api.models.Subscription

/**
 * 
 * @param meta 
 * @param profileId 
 * @param participantState 
 * @param participantType 
 * @param notificationWayList 
 * @param subscriptionList 
 */
data class Participation (

    val meta: ObjectInfo? = null,
    val profileId: kotlin.String? = null,
    val participantState: ParticipantState? = null,
    val participantType: ParticipantType? = null,
    val notificationWayList: kotlin.Array<NotificationWay>? = null,
    val subscriptionList: kotlin.Array<Subscription>? = null
) {
}