/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models


/**
 * 
 * @param regionStorageId 
 * @param countryId 
 * @param regionId 
 * @param cityId 
 * @param timeZone 
 * @param location 
 * @param defaultName 
 * @param order 
 * @param isDeleted 
 * @param id 
 */
data class Place (

    val regionStorageId: kotlin.Int? = null,
    val countryId: kotlin.Int? = null,
    val regionId: kotlin.Int? = null,
    val cityId: kotlin.Int? = null,
    val timeZone: kotlin.String? = null,
    val location: kotlin.Array<kotlin.Double>? = null,
    val defaultName: kotlin.String? = null,
    val order: kotlin.Int? = null,
    val isDeleted: kotlin.Boolean? = null,
    val id: kotlin.Int? = null
) {
}