/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models


/**
 * 
 * @param priceWithoutDiscount 
 * @param discount 
 * @param salePrice 
 * @param currencyCode 
 * @param prepayment 
 * @param expences 
 * @param takePrice 
 */
data class PriceProperties (

    val priceWithoutDiscount: kotlin.Double? = null,
    val discount: kotlin.Double? = null,
    val salePrice: kotlin.Double? = null,
    val currencyCode: kotlin.String? = null,
    val prepayment: kotlin.Double? = null,
    val expences: kotlin.Double? = null,
    val takePrice: kotlin.Double? = null
) {
}