/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.ContactItem
import net.torrow.api.models.Utm

/**
 * 
 * @param timeZone 
 * @param language 
 * @param name 
 * @param placeId 
 * @param contact 
 * @param partnerId 
 * @param programId 
 * @param utm 
 */
data class RegistrationUserInfo (

    val timeZone: kotlin.String? = null,
    val language: kotlin.String? = null,
    val name: kotlin.String? = null,
    val placeId: kotlin.Int? = null,
    val contact: ContactItem? = null,
    val partnerId: kotlin.String? = null,
    val programId: kotlin.String? = null,
    val utm: Utm? = null
) {
}