/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models


/**
 * 
 * @param caseId 
 * @param userMessage 
 * @param checkVersion 
 * @param isNeedAnnouncement 
 */
data class ReturnOrderReq (

    val caseId: kotlin.String? = null,
    val userMessage: kotlin.String? = null,
    val checkVersion: kotlin.Boolean? = null,
    val isNeedAnnouncement: kotlin.Boolean? = null
) {
}