/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.AccountType

/**
 * 
 * @param accountName 
 * @param type 
 * @param language 
 * @param captcha 
 * @param inviteSessionId 
 * @param regionStorageId 
 */
data class SendCodeReq (

    val accountName: kotlin.String? = null,
    val type: AccountType? = null,
    val language: kotlin.String? = null,
    val captcha: kotlin.String? = null,
    val inviteSessionId: kotlin.String? = null,
    val regionStorageId: kotlin.Int? = null
) {
}