/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models


/**
 * 
 * @param sessionId 
 * @param codeLifetimeSeconds 
 * @param nextAvailableUsageTime 
 */
data class SendCodeResp (

    val sessionId: kotlin.String? = null,
    val codeLifetimeSeconds: kotlin.Int? = null,
    val nextAvailableUsageTime: java.time.LocalDateTime? = null
) {
}