/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.SessionDurationType
import net.torrow.api.models.SessionPrecisionType
import net.torrow.api.models.StateManagementType
import net.torrow.api.models.TimeSelectionType

/**
 * 
 * @param sessionDurationType 
 * @param timeSelectionType 
 * @param stateManagementType 
 * @param defaultDuration 
 * @param defaultStartTime 
 * @param defaultFinishTime 
 * @param sessionPrecisionType 
 * @param maxSessionDuration 
 * @param minSessionDuration 
 */
data class SessionDurationProperties (

    val sessionDurationType: SessionDurationType? = null,
    val timeSelectionType: TimeSelectionType? = null,
    val stateManagementType: StateManagementType? = null,
    val defaultDuration: kotlin.Int? = null,
    val defaultStartTime: kotlin.Int? = null,
    val defaultFinishTime: kotlin.Int? = null,
    val sessionPrecisionType: SessionPrecisionType? = null,
    val maxSessionDuration: kotlin.Int? = null,
    val minSessionDuration: kotlin.Int? = null
) {
}