/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.StepParameter

/**
 * 
 * @param stepOrder 
 * @param stepType 
 * @param description 
 * @param stepParameterList 
 */
data class StepDescription (

    val stepOrder: kotlin.Int? = null,
    val stepType: kotlin.Int? = null,
    val description: kotlin.String? = null,
    val stepParameterList: kotlin.Array<StepParameter>? = null
) {
}