/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.TorrowErrorClient

/**
 * 
 * @param &#x60;data&#x60; 
 * @param error 
 */
data class StringObjectDictionaryIEnumerableIftttResponse (

    val `data`: kotlin.Array<kotlin.collections.Map<kotlin.String, kotlin.Any>>? = null,
    val error: TorrowErrorClient? = null
) {
}