/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models


/**
 * 
 * Values: UNKNOWN,ACCOUNT,USER,PARTICIPANT,PERSONALLINK,EVENT,SUBSCRIPTION,ANNOUNCEMENT,REVIEW,REMINDER,FILE,ITEMLINK,ACTIONHISTORY,DEVICE,SHORTURL,USERDELIVERYWAY,USERLINK,FILEHASH,FEEDBACKMESSAGE,FEEDBACKSCORE,NUMERATOR,PAYMENT,INTEGRATIONCONFIG,EXTERNALAUTH,ACCOUNTINGTRANSACTION,CONTEXT,CONTACT,NOTE,CASE,SERVICE,CASEPARTICIPANT,GOAL,RESOURCE,CALENDAR,ORDERPART,SURVEY,SURVEYRESPONSE,ADVISEDITEM,LOYALTYSYSTEM,LOYALTYCARD,REFERRALPROGRAM,LOYALTYCARDSUBSCRIPTION,DICTHOBBY
 */
enum class TorrowObjectType(val value: kotlin.String){
    UNKNOWN("Unknown"),// :/
    ACCOUNT("Account"),// :/
    USER("User"),// :/
    PARTICIPANT("Participant"),// :/
    PERSONALLINK("PersonalLink"),// :/
    EVENT("Event"),// :/
    SUBSCRIPTION("Subscription"),// :/
    ANNOUNCEMENT("Announcement"),// :/
    REVIEW("Review"),// :/
    REMINDER("Reminder"),// :/
    FILE("File"),// :/
    ITEMLINK("ItemLink"),// :/
    ACTIONHISTORY("ActionHistory"),// :/
    DEVICE("Device"),// :/
    SHORTURL("ShortUrl"),// :/
    USERDELIVERYWAY("UserDeliveryWay"),// :/
    USERLINK("UserLink"),// :/
    FILEHASH("FileHash"),// :/
    FEEDBACKMESSAGE("FeedbackMessage"),// :/
    FEEDBACKSCORE("FeedbackScore"),// :/
    NUMERATOR("Numerator"),// :/
    PAYMENT("Payment"),// :/
    INTEGRATIONCONFIG("IntegrationConfig"),// :/
    EXTERNALAUTH("ExternalAuth"),// :/
    ACCOUNTINGTRANSACTION("AccountingTransaction"),// :/
    CONTEXT("Context"),// :/
    CONTACT("Contact"),// :/
    NOTE("Note"),// :/
    CASE("Case"),// :/
    SERVICE("Service"),// :/
    CASEPARTICIPANT("CaseParticipant"),// :/
    GOAL("Goal"),// :/
    RESOURCE("Resource"),// :/
    CALENDAR("Calendar"),// :/
    ORDERPART("OrderPart"),// :/
    SURVEY("Survey"),// :/
    SURVEYRESPONSE("SurveyResponse"),// :/
    ADVISEDITEM("AdvisedItem"),// :/
    LOYALTYSYSTEM("LoyaltySystem"),// :/
    LOYALTYCARD("LoyaltyCard"),// :/
    REFERRALPROGRAM("ReferralProgram"),// :/
    LOYALTYCARDSUBSCRIPTION("LoyaltyCardSubscription"),// :/
    DICTHOBBY("DictHobby");// :/
}