/**
 * Torrow API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package net.torrow.api.models

import net.torrow.api.models.TimetableCase
import net.torrow.api.models.TorrowItem
import net.torrow.api.models.WorkloadPeriod

/**
 * 
 * @param name 
 * @param item 
 * @param workload 
 * @param timetable 
 */
data class WorkloadInfo (

    val name: kotlin.String? = null,
    val item: TorrowItem? = null,
    val workload: kotlin.Array<WorkloadPeriod>? = null,
    val timetable: kotlin.Array<TimetableCase>? = null
) {
}